#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"
message=$(cat "$1")
requiredPattern="^CSF-[0-9]+: .+$"
if ! echo "$message" | grep -Eq "$requiredPattern"; then
  echo "-"
  echo "-"
  echo "-"
  echo ":rotating_light: Wrong commit message! :confused:"
  echo "The commit message must have this format:"
  echo "CSF-Ticket No: any commit message"
  echo "-"
  echo "Your commit message was:"
  echo "$message"
  echo "-"
  exit 1
fi
